project:
  name: theflash
  owner: quickstart-eng@amazon.com
  s3_object_acl: public-read
  #s3_bucket: tcat-theflash-i3lsqt27
  s3_enable_sig_v2: True # When v2 signature is enabled, the bastion bootstrap fails to GET THE SCRIPT!
  regions:
    - us-west-2

tests:
#  jfrog-product-ami:
#    parameters:
#      AvailabilityZone: "$[taskcat_genaz_1]"
#      KeyPairName: "$[taskcat_getkeypair]"
#      ArtifactVersion: 7.1.0
#      JFrogProduct: jfrog-artifactory-jcr
#      ArtifactRepoUrl:  https://solengha.jfrog.io/solengha/tr-rpm
#      RemoteAccessCidr: "10.0.0.0/16"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "theflash/"
#    template: templates/jfrog-ami-master.template.yaml
#    regions:
#      - us-west-2
#  jfrog-container-registry-ec2-mysql:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      JcrVersion: 7.1.0
#      RemoteAccessCidr: "10.0.0.0/16"
#      DatabaseEngine: MySQL
#      AccessCidr: "10.0.0.0/16"
#      AvailabilityZones: "$[taskcat_genaz_2]"
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "theflash/"
#      KeystorePassword: "$[taskcat_genpass_8A]"
#      AnsibleVaultPass: "$[taskcat_genpass_8A]"
#      JcrServerName: "artifactory"
#      SmCertName: "override"
#      MasterKey: "override"
#      MultiAzDatabase: "false"
#    template: templates/jfrog-container-registry-ec2-master.template.yaml
#    regions:
#      - us-west-2
#  jfrog-container-registry-ec2-postgres:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      JcrVersion: 7.2.0
#      RemoteAccessCidr: "10.0.0.0/16"
#      AccessCidr: "10.0.0.0/16"
#      AvailabilityZones: "$[taskcat_genaz_2]"
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "theflash/"
#      KeystorePassword: "$[taskcat_genpass_8A]"
#      AnsibleVaultPass: "$[taskcat_genpass_8A]"
#      JcrServerName: "artifactory"
#      SmCertName: "override"
#      MasterKey: "override"
#      MultiAzDatabase: "false"
#    template: templates/jfrog-container-registry-ec2-master.template.yaml
#    regions:
#      - us-west-2
#  jfrog-container-registry-ecs-mysql:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      RemoteAccessCidr: "10.0.0.0/16"
#      AccessCidr: "10.0.0.0/16"
#      AvailabilityZones: "$[taskcat_genaz_2]"
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "theflash/"
#      DatabaseInstance: "db.m5.large"
#      DatabaseEngine: MySQL
#      JcrVersion: "7.0.0"
#      ReleaseStage: "BETA"
#      NumberOfSecondary: "2"
#      AnsibleVaultPass: "$[taskcat_genpass_8A]"
#      ArtifactoryServerName: "artifactory"
#      MasterKey: "override"
#      SmCertName: "override"
#    template: templates/jfrog-container-registry-ecs-master.template.yaml
#    regions:
#      - us-west-2
#  jfrog-container-registry-eks-east-mysql:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      AvailabilityZones: "$[taskcat_genaz_3]"
#      DatabaseEngine: MySQL
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "theflash/"
#      DatabaseInstance: "db.m5.large"
#      JcrVersion: "7.1.0"
#      ReleaseStage: BETA
#      ArtifactoryServerName: "artifactory"
#      MasterKey: "override"
#      SmCertName: "override"
#      MultiAzDatabase: "false"
#    template: templates/jfrog-container-registry-eks-master.template.yaml
#    regions:
#      - us-east-1
#  jfrog-container-registry-eks-west-postgres:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      AvailabilityZones: "$[taskcat_genaz_3]"
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "theflash/"
#      DatabaseInstance: "db.m5.large"
#      JcrVersion: "7.1.0"
#      ReleaseStage: BETA
#      ArtifactoryServerName: "artifactory"
#      MasterKey: "override"
#      SmCertName: "override"
#      MultiAzDatabase: "false"
#    template: templates/jfrog-container-registry-eks-master.template.yaml
#    regions:
#      - us-west-2

