---

# Tasks to configure Artifactory JCR version 7
- name: Template of the properties and certs as required by Artifactory
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: artifactory
    group: artifactory
    mode: '0664'
  loop:
    - src: binarystore.xml.j2
      dest: /var/opt/jfrog/artifactory/etc/artifactory/binarystore.xml
    - src: master.key.j2
      dest: /var/opt/jfrog/artifactory/etc/security/master.key
    - src: system.yaml.j2
      dest: /var/opt/jfrog/artifactory/etc/system.yaml
    - src: certificate.pem.j2
      dest: "{{ ssl_dir }}/cert.pem"
    - src: certificate.key.j2
      dest: "{{ key_dir }}/cert.key"
  notify:
    - enable artifactory
    - restart artifactory
    - restart nginx

- name: Cleanup AMI from original Artifactory start
  file:
    path: /var/opt/jfrog/artifactory/etc/security/join.key
    state: absent
  notify:
    - restart artifactory
