---

- name: Add Artifactory Repo
  yum_repository:
    name: bintray--jfrog-artifactory-pro-rpms
    description: bintray--jfrog-artifactory-pro-rpms
    baseurl: https://jfrog.bintray.com/artifactory-pro-rpms
    gpgcheck: no
    enabled: yes

- name: Install Artifactory from RPM
  yum:
    name: "jfrog-artifactory-pro-{{ artifactory_version }}"
    state: installed
    releasever: "{{ artifactory_version }}"
    enablerepo: bintray--jfrog-artifactory-pro-rpms
    disablerepo: "epel,amzn-main,amzn-updates"
  notify: Enable Artifactory

- name: Update Java
  package:
   name:
    - "{{ java_version }}"
    - nginx
   state: present

- name: Configure Java
  alternatives:
    name: java
    path: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
  when: ansible_distribution == "Amazon"
