---

- name: Set tomcat location
  set_fact:
    jcr_tomcat_loc: /var/opt/jfrog/artifactory/bootstrap/artifactory/tomcat/lib

- name: Configure an Instance to host JCR
  include: "{{ my_tasks.name }}"
  when: ecs_deployment == false
  loop:
    - name: shared_configure_db_ssl.yml
    - name: configure_7.yml
    - name: nginx-setup.yml
  loop_control:
    loop_var: my_tasks

- name: Configure ECS EC2 Node to host an Artifactory Container
  include: configure_ecs.yml
  when: ecs_deployment == true
