---

# Tasks for configuring NGINX for Artifactory
- name: Configure main NGINX conf file.
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0755'
  notify: restart nginx


- name: Configure the Artifactory NGINX conf
  template:
    src: artifactory.conf.j2
    dest: /etc/nginx/conf.d/artifactory.conf
    owner: root
    group: root
    mode: '0755'
  notify: restart nginx

- name: Change to host python for Yum
  set_fact:
    ansible_python_interpreter: /usr/bin/python
  when: artifactory_version.split('.')[0]|int == 7
  
- name: Configure selinux for nginx
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
